# Generated by Django 4.2.16 on 2024-12-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="message_html",
            field=models.TextField(default="null", editable=False),
            preserve_default=False,
        ),
    ]
